/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package controller;

/**
 *
 * @author wmalf
 */
import java.io.IOException;
import java.io.OutputStream;
import javax.servlet.*;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.*;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;

import dao.ReportDAO;
import java.awt.Color;
import model.Report;

@WebServlet("/DownloadReportPDFServlet")
public class DownloadReportPDFServlet extends HttpServlet {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        int reportId = Integer.parseInt(request.getParameter("reportId"));
        ReportDAO dao = new ReportDAO();
        Report report = dao.getReportById(reportId);

        if (report != null) {
            response.setContentType("application/pdf");
            response.setHeader("Content-Disposition", "attachment;filename=report_" + reportId + ".pdf");

            try {
                OutputStream out = response.getOutputStream();
                Document document = new Document();
                PdfWriter.getInstance(document, out);

                document.open();

                // 1. Add a logo (optional: use a real image path if needed)
                try {
                    Image logo = Image.getInstance(getServletContext().getRealPath("/images/logo.png")); // optional
                    logo.scaleToFit(100, 100);
                    logo.setAlignment(Image.ALIGN_RIGHT);
                    document.add(logo);
                } catch (Exception imgErr) {
                    // If logo is missing, ignore
                }

                // 2. Add a title section
                Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Color.BLUE);
                Font sectionFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Color.DARK_GRAY);
                Font contentFont = FontFactory.getFont(FontFactory.HELVETICA, 12);

                Paragraph title = new Paragraph("Car Rental System Report", titleFont);
                title.setAlignment(Element.ALIGN_CENTER);
                title.setSpacingAfter(15);
                document.add(title);

                // 3. Add report metadata
                document.add(new Paragraph("Report Type: " + report.getReportType(), sectionFont));
                document.add(new Paragraph("Generated On: " + report.getGeneratedDate(), contentFont));
                document.add(new Paragraph("Generated By (User ID): " + report.getGeneratedBy(), contentFont));
                document.add(Chunk.NEWLINE);

                // 4. Add content section
                document.add(new Paragraph("Report Content:", sectionFont));
                Paragraph body = new Paragraph(report.getContent(), contentFont);
                body.setSpacingBefore(10);
                body.setAlignment(Element.ALIGN_JUSTIFIED);
                document.add(body);
 
                document.close();

            } catch (com.lowagie.text.DocumentException e) {
                e.printStackTrace();
                response.getWriter().println("Failed to generate PDF: " + e.getMessage());
            }

        } else {
            response.getWriter().println("Report not found.");
        }
    }
}
